"""
SupplyShield — Rule-Based Guidance Engine

Provides fast, deterministic, rule-based recommendations based on
the SHAP explainability output of the global predictive model.
"""

def generate_rule_based_guidance(explanation: dict) -> list[str]:
    """
    Generate actionable recommendations based on the prediction and SHAP explanation.
    
    Args:
        explanation: Dictionary generated by shap_explainer.generate_explanation_dict
        
    Returns:
        List of actionable recommendation strings.
    """
    prediction = explanation.get("prediction", {})
    explainability = explanation.get("explainability", {})
    
    is_delayed = prediction.get("is_delayed", False)
    prob = prediction.get("delay_probability", 0.0)
    top_drivers = explainability.get("top_drivers", [])
    
    recommendations = []
    
    if not is_delayed:
        recommendations.append("Route appears clear. Proceed with standard logistics plan.")
        return recommendations
        
    recommendations.append(f"High risk of delay detected ({(prob * 100):.1f}% probability).")
    
    # Process top drivers to generate specific mitigation steps
    for driver in top_drivers:
        feature = driver["feature"]
        impact = driver["impact"]
        
        # We only care about features that *increase* delay
        if impact > 0:
            if feature == "weather_condition":
                recommendations.append("Mitigation: Severe weather conditions detected. Consider re-routing or switching to weather-resistant transport modes.")
            elif feature == "vehicle_type":
                recommendations.append("Mitigation: Vehicle type correlates with delays for this route. Consider upgrading to a faster or more reliable vehicle.")
            elif feature == "distance_km":
                recommendations.append("Mitigation: Distance is a significant factor. Consider cross-docking or expedited staging at intermediate hubs.")
            elif feature == "delivery_mode":
                recommendations.append("Mitigation: The current delivery mode (e.g. Standard) is high-risk here. Upgrade to express shipping.")
            elif feature == "region":
                recommendations.append("Mitigation: Destination region is experiencing logistical delays. Check local congestion alerts.")
                
    if not recommendations[1:]:
        recommendations.append("Review standard delay protocols with the delivery partner.")
        
    return recommendations
