"""
SupplyShield — Rule-Based Guidance Engine

Provides fast, deterministic, rule-based recommendations based on
the SHAP explainability output of the global predictive model.
"""

def generate_rule_based_guidance(explanation: dict) -> list[str]:
    """
    Generate actionable recommendations based on the prediction and SHAP explanation.
    
    Args:
        explanation: Dictionary generated by shap_explainer.generate_explanation_dict
        
    Returns:
        List of actionable recommendation strings.
    """
    prediction = explanation.get("prediction", {})
    explainability = explanation.get("explainability", {})
    
    is_delayed = prediction.get("is_delayed", False)
    prob = prediction.get("delay_probability", 0.0)
    top_drivers = explainability.get("top_drivers", [])
    
    recommendations = []
    
    if not is_delayed:
        recommendations.append("Route appears clear. Proceed with standard logistics plan.")
        return recommendations
        
    recommendations.append(f"High risk of delay detected ({(prob * 100):.1f}% probability).")
    
    # Process top drivers to generate specific mitigation steps
    for driver in top_drivers:
        feature = driver["feature"]
        impact = driver["impact"]
        
        # We only care about features that *increase* delay
        if impact > 0:
            if feature == "weather":
                # Assuming high values (e.g., 2, 3) indicate bad weather based on our encoding
                recommendations.append("Mitigation: Severe weather detected. Re-route or switch to weather-resistant transport.")
            elif feature == "traffic":
                recommendations.append("Mitigation: Heavy traffic expected. Delay departure by 2 hours or use alternate highways.")
            elif feature == "vehicle_type":
                recommendations.append("Mitigation: Current vehicle type correlates with delays for this route. Consider upgrading to a larger or more reliable vehicle.")
            elif feature == "distance_km":
                recommendations.append("Mitigation: Distance is a significant factor. Consider split shipments or cross-docking midway.")
                
    if not recommendations[1:]:
        recommendations.append("Review standard delay protocols with the delivery partner.")
        
    return recommendations
